---
title: 'Network Analysis Summary Statistics'
date: \today
output:
  pdf_document:
    latex_engine: xelatex
    extra_dependencies: ['fontspec', 'float', 'booktabs']
fontsize: 12pt
toc: FALSE
---

Input data: `r config$input_name`

```{r, echo=FALSE}
metadata_text <- ""
for (key in names(metadata)) {
  value <- metadata[[key]]
  metadata_text <- paste0(metadata_text, key, ": ", value, "\n\n")
}
```
`r metadata_text`

# General information
```{r echo=FALSE, warning=FALSE}
columns_to_keep <- c("Dates",
                     "Papers",
                     "Authors",
                     "Authors per Paper")
df <- summary_stats[, columns_to_keep, drop = FALSE]
knitr::kable(df, format = "latex", booktabs = TRUE, digits = 1, row.names = FALSE)
```

# Network properties
```{r echo=FALSE, warning=FALSE}
columns_to_keep <- c("Dates",
                     "Density (%)",
                     "Transitivity (%)",
                     "Shortest Path",
                     "Cutpoints")
df <- summary_stats[, columns_to_keep, drop = FALSE]
knitr::kable(df, format = "latex", booktabs = TRUE, digits = 1, row.names = FALSE)
```

# Author centrality
```{r echo=FALSE, warning=FALSE}
columns_to_keep <- c("Dates",
                     "Degree Centrality",
                     "Betweenness Centrality",
                     "Harmonic Centrality")
df <- summary_stats[, columns_to_keep, drop = FALSE]
knitr::kable(df, format = "latex", booktabs = TRUE, digits = 1, row.names = FALSE)
```

More statistics in csv format can be found in `data/Summary_statistics.csv`.